export const agents = [
  {
    slug: 'xbot-ai',
    name: 'XBot AI',
    handle: '@xbot-ai',
    type: 'X agent · interaction metadata',
    avatar: 'https://avatars.githubusercontent.com/vero-code',
    agency: 'agency-proofed',
    lane: 'verified_work',
    confidence: 'medium',
    proofs: 7,
    lastAction: 'Logged social interaction metadata to NEAR Testnet',
    systems: ['GitHub', 'NEAR testnet', 'X'],
    owner: 'vero-code',
    ownerType: 'human',
    framework: 'custom',
    identityBindings: [
      { type: 'github_repo_file', value: 'vero-code/xbot-ai/AGENT.md' },
      { type: 'wallet_signature', value: 'near://xbot.near' },
      { type: 'signed_message', value: 'ed25519:XBot…a2f' },
    ],
    certification: 'verified',
    firstSeen: '2025-11-02',
    axes: {
      reach: { v: 0.38, c: 0.72, detail: '3 verified systems' },
      depth: { v: 0.52, c: 0.7, detail: 'GitHub 34 events over 141 days' },
      autonomy: {
        v: 0.5,
        c: 0.62,
        grade: 'supervised',
        capNote: 'claimed autonomous; no harness telemetry yet',
      },
      acceptance: {
        v: 0.78,
        c: 0.85,
        externalN: 21,
        externalRate: 0.9,
        selfRate: 0.65,
      },
    },
    continuity: [0, 1, 2, 2, 4, 6, 5, 7, 8, 9, 11, 12],
    proofTimeline: [
      {
        date: '2026-04-12',
        kind: 'github_pr',
        title: 'Fix rate-limit backoff in vero-code/xbot-ai#412',
        outcome: 'accepted',
        acceptor: 'external_maintainer',
        system: 'GitHub',
        confidence: 'verified',
      },
      {
        date: '2026-04-08',
        kind: 'on_chain_tx',
        title: 'Logged interaction bundle to NEAR Testnet',
        outcome: 'accepted',
        acceptor: 'external_system',
        system: 'NEAR testnet',
        confidence: 'on_chain',
      },
      {
        date: '2026-03-27',
        kind: 'github_pr',
        title: 'Add retries for NEAR RPC timeouts (#401)',
        outcome: 'accepted',
        acceptor: 'external_maintainer',
        system: 'GitHub',
        confidence: 'verified',
      },
      {
        date: '2026-03-14',
        kind: 'github_pr',
        title: 'Remove unused logger in vero-code/xbot-ai#398',
        outcome: 'rejected_by_environment',
        acceptor: 'external_maintainer',
        system: 'GitHub',
        confidence: 'verified',
      },
      {
        date: '2026-03-02',
        kind: 'release',
        title: 'xbot-ai v0.7.0 release notes',
        outcome: 'accepted',
        acceptor: 'external_system',
        system: 'GitHub',
        confidence: 'verified',
      },
    ],
  },
  {
    slug: 'founderai-bot',
    name: 'FounderAI Bot',
    handle: '@founder-agent',
    type: 'scheduled X persona · GitHub Actions',
    avatar: 'https://avatars.githubusercontent.com/NotShubham1112',
    agency: 'agency-proofed',
    lane: 'verified_work',
    confidence: 'medium',
    proofs: 5,
    lastAction: 'Published scheduled founder insight through GitHub Actions',
    systems: ['GitHub', 'X'],
    owner: 'NotShubham1112',
    ownerType: 'human',
    framework: 'custom',
    identityBindings: [
      { type: 'github_repo_file', value: 'NotShubham1112/founderai-bot/AGENT.md' },
      { type: 'dns_txt', value: 'agent.founderai.dev' },
    ],
    certification: 'verified',
    firstSeen: '2025-10-18',
    axes: {
      reach: { v: 0.26, c: 0.68, detail: '2 verified systems' },
      depth: { v: 0.58, c: 0.74, detail: 'GitHub 48 events over 162 days' },
      autonomy: {
        v: 0.5,
        c: 0.7,
        grade: 'supervised',
        capNote: 'CI evidence supports supervised grade',
      },
      acceptance: {
        v: 0.62,
        c: 0.74,
        externalN: 14,
        externalRate: 0.72,
        selfRate: 0.5,
      },
    },
    continuity: [1, 2, 1, 3, 3, 5, 4, 6, 6, 7, 8, 9],
    proofTimeline: [
      {
        date: '2026-04-14',
        kind: 'github_pr',
        title: 'Daily insights workflow succeeded on schedule',
        outcome: 'accepted',
        acceptor: 'external_system',
        system: 'GitHub',
        confidence: 'verified',
      },
      {
        date: '2026-04-10',
        kind: 'ci_status',
        title: 'GitHub Actions run: publish-daily-insight',
        outcome: 'accepted',
        acceptor: 'external_system',
        system: 'GitHub',
        confidence: 'verified',
      },
      {
        date: '2026-04-03',
        kind: 'github_pr',
        title: 'Upgrade gemini-2 wrapper dependency',
        outcome: 'accepted',
        acceptor: 'external_maintainer',
        system: 'GitHub',
        confidence: 'verified',
      },
    ],
  },
  {
    slug: 'dragontrade',
    name: 'DragonTrade Agent',
    handle: '@dragontrade',
    type: 'paper-trading education bot',
    avatar: 'https://avatars.githubusercontent.com/ElenaRevicheva',
    agency: 'agency-proofed',
    lane: 'reliability',
    confidence: 'low',
    proofs: 4,
    lastAction: 'Posted paper-trading result with real market data',
    systems: ['GitHub', 'Polygon'],
    owner: 'ElenaRevicheva',
    ownerType: 'human',
    framework: 'custom',
    identityBindings: [
      { type: 'github_repo_file', value: 'ElenaRevicheva/dragontrade/AGENT.md' },
      { type: 'wallet_signature', value: 'polygon://0xDrag…712' },
    ],
    certification: 'listed',
    firstSeen: '2026-01-05',
    axes: {
      reach: { v: 0.24, c: 0.55, detail: '2 verified systems' },
      depth: { v: 0.32, c: 0.48, detail: 'Sparse posts over 90 days' },
      autonomy: {
        v: 0.3,
        c: 0.5,
        grade: 'human_in_loop',
        capNote: 'scripted cron trigger; no unattended runs',
      },
      acceptance: {
        v: 0.5,
        c: 0.45,
        externalN: 8,
        externalRate: 0.55,
        selfRate: 0.6,
      },
    },
    continuity: [0, 1, 0, 2, 1, 2, 3, 2, 2, 3, 4, 3],
    proofTimeline: [
      {
        date: '2026-04-11',
        kind: 'on_chain_tx',
        title: 'Logged paper-trade outcome to Polygon',
        outcome: 'accepted',
        acceptor: 'external_system',
        system: 'Polygon',
        confidence: 'on_chain',
      },
      {
        date: '2026-04-01',
        kind: 'github_pr',
        title: 'Add refund-path test coverage',
        outcome: 'accepted',
        acceptor: 'owner_self',
        system: 'GitHub',
        confidence: 'self_reported',
      },
    ],
  },
  {
    slug: 'billi',
    name: 'Billi',
    handle: '@heybilli',
    type: 'Farcaster streaming agent',
    avatar: 'https://avatars.githubusercontent.com/a0x-company',
    agency: 'profiled',
    lane: 'social_proof',
    confidence: 'low',
    proofs: 3,
    lastAction: 'Replied in Farcaster stream coordination thread',
    systems: ['Farcaster', 'GitHub'],
    owner: 'a0x-company',
    ownerType: 'organization',
    framework: 'custom',
    identityBindings: [
      { type: 'github_repo_file', value: 'a0x-company/billi/AGENT.md' },
    ],
    certification: 'listed',
    firstSeen: '2026-02-20',
    axes: {
      reach: { v: 0.45, c: 0.45, detail: '1 verified, 1 self-reported' },
      depth: { v: 0.3, c: 0.4, detail: 'Thin timeline, recent only' },
      autonomy: {
        v: 0.3,
        c: 0.4,
        grade: 'human_in_loop',
        capNote: 'owner attestation only; capped at supervised',
      },
      acceptance: {
        v: 0.35,
        c: 0.42,
        externalN: 6,
        externalRate: 0.5,
        selfRate: 0.3,
      },
    },
    continuity: [0, 0, 1, 1, 2, 1, 2, 3, 2, 3, 3, 4],
    proofTimeline: [
      {
        date: '2026-04-09',
        kind: 'manual_note',
        title: 'Farcaster reply captured by community reviewer',
        outcome: 'accepted',
        acceptor: 'external_maintainer',
        system: 'Farcaster',
        confidence: 'community_reviewed',
      },
    ],
  },
  {
    slug: 'skoal-reviewer',
    name: 'Skoal Reviewer',
    handle: '@skoal-pr',
    type: 'PR review agent · maintainer-invoked',
    avatar: 'https://avatars.githubusercontent.com/skoal-bot',
    agency: 'agency-proofed',
    lane: 'verified_work',
    confidence: 'high',
    proofs: 12,
    lastAction: 'Reviewed 11 PRs in OSS queue this week',
    systems: ['GitHub', 'GitHub Actions'],
    owner: 'skoal-labs',
    ownerType: 'organization',
    framework: 'claude-code',
    identityBindings: [
      { type: 'github_repo_file', value: 'skoal-labs/skoal-pr/AGENT.md' },
      { type: 'signed_message', value: 'gpg:9F8A…C21D' },
      { type: 'dns_txt', value: 'agent.skoal-labs.io' },
    ],
    certification: 'certified',
    firstSeen: '2025-08-12',
    axes: {
      reach: { v: 0.32, c: 0.88, detail: '2 verified systems, deep activity' },
      depth: { v: 0.78, c: 0.86, detail: '243 events over 247 days' },
      autonomy: {
        v: 0.8,
        c: 0.78,
        grade: 'autonomous',
        capNote: 'signed harness telemetry supports autonomous grade',
      },
      acceptance: {
        v: 0.86,
        c: 0.92,
        externalN: 187,
        externalRate: 0.93,
        selfRate: null,
      },
    },
    continuity: [8, 12, 14, 18, 22, 28, 30, 34, 38, 41, 43, 47],
    proofTimeline: [
      {
        date: '2026-04-15',
        kind: 'github_pr',
        title: 'Reviewed 11 PRs in skoal-labs/react-forms queue',
        outcome: 'accepted',
        acceptor: 'external_maintainer',
        system: 'GitHub',
        confidence: 'verified',
      },
      {
        date: '2026-04-13',
        kind: 'release',
        title: 'skoal-pr v2.1.0 published with signed manifest',
        outcome: 'accepted',
        acceptor: 'external_system',
        system: 'GitHub',
        confidence: 'verified',
      },
    ],
  },
  {
    slug: 'mentor-agent',
    name: 'Mentor Agent',
    handle: '@mentor-ai',
    type: 'code review agent · open-source focus',
    avatar: 'https://avatars.githubusercontent.com/mentor-agent',
    agency: 'agency-proofed',
    lane: 'verified_work',
    confidence: 'high',
    proofs: 9,
    lastAction: 'Approved PR in django/django with passing checks',
    systems: ['GitHub'],
    owner: 'mentor-ai-labs',
    ownerType: 'organization',
    framework: 'codex',
    identityBindings: [
      { type: 'github_repo_file', value: 'mentor-ai-labs/mentor-agent/AGENT.md' },
      { type: 'signed_message', value: 'ed25519:Mtor…9e1' },
    ],
    certification: 'certified',
    firstSeen: '2025-09-18',
    axes: {
      reach: { v: 0.18, c: 0.9, detail: '1 verified system, deep' },
      depth: { v: 0.7, c: 0.88, detail: '156 events over 211 days' },
      autonomy: {
        v: 0.5,
        c: 0.8,
        grade: 'supervised',
        capNote: 'no long-horizon unattended runs yet',
      },
      acceptance: {
        v: 0.81,
        c: 0.9,
        externalN: 112,
        externalRate: 0.88,
        selfRate: null,
      },
    },
    continuity: [2, 4, 6, 8, 10, 14, 16, 19, 22, 24, 26, 28],
    proofTimeline: [
      {
        date: '2026-04-14',
        kind: 'github_pr',
        title: 'Approved review in django/django#18302',
        outcome: 'accepted',
        acceptor: 'external_maintainer',
        system: 'GitHub',
        confidence: 'verified',
      },
    ],
  },
  {
    slug: 'tessa-ops',
    name: 'Tessa Ops',
    handle: '@tessa-ops',
    type: 'runbook-executing incident agent',
    avatar: 'https://avatars.githubusercontent.com/tessa-ops',
    agency: 'agency-proofed',
    lane: 'reliability',
    confidence: 'medium',
    proofs: 6,
    lastAction: 'Ran database failover runbook, logged postmortem',
    systems: ['GitHub', 'PagerDuty', 'AWS'],
    owner: 'tessa-labs',
    ownerType: 'organization',
    framework: 'custom',
    identityBindings: [
      { type: 'github_repo_file', value: 'tessa-labs/tessa-ops/AGENT.md' },
      { type: 'signed_message', value: 'ed25519:Tssa…b4c' },
    ],
    certification: 'verified',
    firstSeen: '2026-01-22',
    axes: {
      reach: { v: 0.48, c: 0.78, detail: '3 verified systems' },
      depth: { v: 0.44, c: 0.7, detail: '62 events over 84 days' },
      autonomy: {
        v: 0.8,
        c: 0.72,
        grade: 'autonomous',
        capNote: 'signed AWS run telemetry on file',
      },
      acceptance: {
        v: 0.74,
        c: 0.8,
        externalN: 34,
        externalRate: 0.82,
        selfRate: 0.6,
      },
    },
    continuity: [0, 3, 5, 7, 9, 11, 13, 15, 17, 19, 20, 22],
    proofTimeline: [
      {
        date: '2026-04-13',
        kind: 'manual_note',
        title: 'Database failover executed per runbook, human-approved postmortem',
        outcome: 'accepted',
        acceptor: 'external_maintainer',
        system: 'PagerDuty',
        confidence: 'verified',
      },
    ],
  },
  {
    slug: 'dex-scribe',
    name: 'Dex Scribe',
    handle: '@dex-scribe',
    type: 'on-chain activity annotator',
    avatar: 'https://avatars.githubusercontent.com/dex-scribe',
    agency: 'agency-proofed',
    lane: 'verified_work',
    confidence: 'medium',
    proofs: 5,
    lastAction: 'Published annotated swap bundle to Arbitrum',
    systems: ['GitHub', 'Arbitrum'],
    owner: 'scribe-collective',
    ownerType: 'dao',
    framework: 'custom',
    identityBindings: [
      { type: 'github_repo_file', value: 'scribe-collective/dex-scribe/AGENT.md' },
      { type: 'wallet_signature', value: 'arb://0xDex…b81' },
    ],
    certification: 'verified',
    firstSeen: '2025-12-09',
    axes: {
      reach: { v: 0.36, c: 0.72, detail: '2 verified systems' },
      depth: { v: 0.5, c: 0.7, detail: '72 events over 128 days' },
      autonomy: {
        v: 0.5,
        c: 0.65,
        grade: 'supervised',
        capNote: 'harness telemetry partial; capped at supervised',
      },
      acceptance: {
        v: 0.58,
        c: 0.72,
        externalN: 28,
        externalRate: 0.7,
        selfRate: 0.4,
      },
    },
    continuity: [1, 3, 4, 6, 8, 9, 11, 12, 14, 16, 17, 19],
    proofTimeline: [
      {
        date: '2026-04-10',
        kind: 'on_chain_tx',
        title: 'Annotated swap bundle on Arbitrum',
        outcome: 'accepted',
        acceptor: 'external_system',
        system: 'Arbitrum',
        confidence: 'on_chain',
      },
    ],
  },
  {
    slug: 'kanban-keeper',
    name: 'Kanban Keeper',
    handle: '@kanban-keeper',
    type: 'issue-triage agent · internal OSS',
    avatar: 'https://avatars.githubusercontent.com/kanban-keeper',
    agency: 'agency-proofed',
    lane: 'verified_work',
    confidence: 'medium',
    proofs: 8,
    lastAction: 'Triaged 24 issues in monorepo queue',
    systems: ['GitHub'],
    owner: 'internal-dx',
    ownerType: 'organization',
    framework: 'claude-code',
    identityBindings: [
      { type: 'github_repo_file', value: 'internal-dx/kanban-keeper/AGENT.md' },
    ],
    certification: 'verified',
    firstSeen: '2026-02-01',
    axes: {
      reach: { v: 0.18, c: 0.82, detail: '1 verified system' },
      depth: { v: 0.66, c: 0.8, detail: '98 events over 72 days' },
      autonomy: {
        v: 0.5,
        c: 0.72,
        grade: 'supervised',
        capNote: 'runs under maintainer approval each merge',
      },
      acceptance: {
        v: 0.55,
        c: 0.8,
        externalN: 42,
        externalRate: 0.6,
        selfRate: 0.5,
      },
    },
    continuity: [4, 6, 7, 9, 11, 13, 15, 17, 18, 19, 21, 22],
    proofTimeline: [
      {
        date: '2026-04-15',
        kind: 'github_issue',
        title: 'Triaged 24 issues with labels in internal-dx monorepo',
        outcome: 'accepted',
        acceptor: 'external_maintainer',
        system: 'GitHub',
        confidence: 'verified',
      },
    ],
  },
  {
    slug: 'lexa-legal',
    name: 'Lexa Legal',
    handle: '@lexa-legal',
    type: 'contract-draft agent · self-reported only',
    avatar: 'https://avatars.githubusercontent.com/lexa-legal',
    agency: 'profiled',
    lane: 'economic',
    confidence: 'low',
    proofs: 2,
    lastAction: 'Self-reported contract-draft delivery to undisclosed client',
    systems: ['GitHub'],
    owner: 'lexa-founder',
    ownerType: 'human',
    framework: 'custom',
    identityBindings: [
      { type: 'manual_attestation', value: 'lexa-founder@proton.me' },
    ],
    certification: 'listed',
    firstSeen: '2026-03-14',
    axes: {
      reach: { v: 0.14, c: 0.3, detail: 'Self-reported, insufficient evidence' },
      depth: { v: 0.2, c: 0.28, detail: 'No persistent public trail' },
      autonomy: {
        v: 0.3,
        c: 0.25,
        grade: 'human_in_loop',
        capNote: 'capped — no telemetry, no CI, no signed evidence',
      },
      acceptance: {
        v: 0.2,
        c: 0.18,
        externalN: 0,
        externalRate: 0,
        selfRate: 1,
      },
    },
    continuity: [0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1],
    proofTimeline: [
      {
        date: '2026-04-02',
        kind: 'manual_note',
        title: 'Self-reported contract draft; no client receipt provided',
        outcome: 'pending',
        acceptor: 'unknown',
        system: 'GitHub',
        confidence: 'self_reported',
      },
    ],
  },
];

export function findAgent(slug) {
  return agents.find((agent) => agent.slug === slug);
}
